export const gaokaoWorks = [
  {
    title: "劝学",
    author: "荀子",
    excerptStart: "君子曰：学不可以已",
    excerptEnd: "用心躁也",
    fullText: [
      "君子曰：学不可以已。",
      "青，取之于蓝，而青于蓝；冰，水为之，而寒于水。",
      "木直中绳，輮以为轮，其曲中规。虽有槁暴，不复挺者，輮使之然也。",
      "故木受绳则直，金就砺则利。",
      "君子博学而日参省乎己，则知明而行无过矣。",
      "吾尝终日而思矣，不如须臾之所学也。",
      "吾尝跂而望矣，不如登高之博见也。",
      "登高而招，臂非加长也，而见者远；顺风而呼，声非加疾也，而闻者彰。",
      "假舆马者，非利足也，而致千里；假舟楫者，非能水也，而绝江河。",
      "君子生非异也，善假于物也。",
      "积土成山，风雨兴焉；积水成渊，蛟龙生焉；",
      "积善成德，而神明自得，圣心备焉。",
      "故不积跬步，无以至千里；不积小流，无以成江海。",
      "骐骥一跃，不能十步；驽马十驾，功在不舍。",
      "锲而舍之，朽木不折；锲而不舍，金石可镂。",
      "蚓无爪牙之利，筋骨之强，上食埃土，下饮黄泉，用心一也。",
      "蟹六跪而二螯，非蛇鳝之穴无可寄托者，用心躁也。"
    ]
  },
  { title: "逍遥游", author: "庄子", excerptStart: "北冥有鱼，其名为鲲", excerptEnd: "圣人无名" },
  { title: "师说", author: "韩愈", excerptStart: "古之学者必有师", excerptEnd: "余嘉其能行古道" },
  { title: "阿房宫赋", author: "杜牧", excerptStart: "六王毕，四海一", excerptEnd: "亦使后人而复哀后人也" },
  { title: "赤壁赋", author: "苏轼", excerptStart: "壬戌之秋，七月既望", excerptEnd: "不知东方之既白" },
  { title: "氓", author: "《诗经》", excerptStart: "氓之蚩蚩", excerptEnd: "亦已焉哉" },
  { title: "离骚", author: "屈原", excerptStart: "帝高阳之苗裔兮", excerptEnd: "来吾道夫先路" },
  { title: "蜀道难", author: "李白", excerptStart: "噫吁嚱", excerptEnd: "侧身西望长咨嗟" },
  { title: "登高", author: "杜甫", excerptStart: "风急天高猿啸哀", excerptEnd: "潦倒新停浊酒杯" },
  { title: "琵琶行", author: "白居易", excerptStart: "浔阳江头夜送客", excerptEnd: "江州司马青衫湿" },
  { title: "锦瑟", author: "李商隐", excerptStart: "锦瑟无端五十弦", excerptEnd: "只是当时已惘然" },
  { title: "虞美人", author: "李煜", excerptStart: "春花秋月何时了", excerptEnd: "恰似一江春水向东流" },
  { title: "念奴娇·赤壁怀古", author: "苏轼", excerptStart: "大江东去", excerptEnd: "一尊还酹江月" },
  { title: "永遇乐·京口北固亭怀古", author: "辛弃疾", excerptStart: "千古江山", excerptEnd: "一片神鸦社鼓" },
  { title: "关雎", author: "《诗经》", excerptStart: "关关雎鸠", excerptEnd: "钟鼓乐之" },
  { title: "蒹葭", author: "《诗经》", excerptStart: "蒹葭苍苍", excerptEnd: "宛在水中沚" },
  { title: "早春呈水部张十八员外", author: "韩愈", excerptStart: "天街小雨润如酥", excerptEnd: "绝胜烟柳满皇都" },
  { title: "观沧海", author: "曹操", excerptStart: "东临碣石", excerptEnd: "歌以咏志" },
  { title: "饮酒", author: "陶渊明", excerptStart: "结庐在人境", excerptEnd: "欲辨已忘言" },
  { title: "木兰诗", author: "乐府诗集", excerptStart: "唧唧复唧唧", excerptEnd: "安能辨我是雄雌" },
  { title: "送杜少府之任蜀州", author: "王勃", excerptStart: "城阙辅三秦", excerptEnd: "儿女共沾巾" },
  { title: "登幽州台歌", author: "陈子昂", excerptStart: "前不见古人", excerptEnd: "独怆然而涕下" },
  { title: "次北固山下", author: "王湾", excerptStart: "客路青山外", excerptEnd: "归雁洛阳边" },
  { title: "使至塞上", author: "王维", excerptStart: "单车欲问边", excerptEnd: "都护在燕然" },
  { title: "闻王昌龄左迁龙标遥有此寄", author: "李白", excerptStart: "杨花落尽子规啼", excerptEnd: "随君直到夜郎西" },
  { title: "行路难", author: "李白", excerptStart: "金樽清酒斗十千", excerptEnd: "直挂云帆济沧海" },
  { title: "观刈麦", author: "白居易", excerptStart: "田家少闲月", excerptEnd: "尽日不能忘" },
  { title: "望岳", author: "杜甫", excerptStart: "岱宗夫如何", excerptEnd: "一览众山小" },
  { title: "春望", author: "杜甫", excerptStart: "国破山河在", excerptEnd: "浑欲不胜簪" },
  { title: "茅屋为秋风所破歌", author: "杜甫", excerptStart: "八月秋高风怒号", excerptEnd: "吾庐独破受冻死亦足" },
  { title: "白雪歌送武判官归京", author: "岑参", excerptStart: "北风卷地白草折", excerptEnd: "雪上空留马行处" },
  { title: "酬乐天扬州初逢席上见赠", author: "刘禹锡", excerptStart: "巴山楚水凄凉地", excerptEnd: "暂凭杯酒长精神" },
  { title: "卖炭翁", author: "白居易", excerptStart: "卖炭翁，伐薪烧炭南山中", excerptEnd: "系向牛头充炭直" },
  { title: "钱塘湖春行", author: "白居易", excerptStart: "孤山寺北贾亭西", excerptEnd: "绿杨阴里白沙堤" },
  { title: "雁门太守行", author: "李贺", excerptStart: "黑云压城城欲摧", excerptEnd: "提携玉龙为君死" },
  { title: "赤壁", author: "杜牧", excerptStart: "折戟沉沙铁未销", excerptEnd: "铜雀春深锁二乔" },
  { title: "泊秦淮", author: "杜牧", excerptStart: "烟笼寒水月笼沙", excerptEnd: "隔江犹唱后庭花" },
  { title: "夜雨寄北", author: "李商隐", excerptStart: "君问归期未有期", excerptEnd: "却话巴山夜雨时" },
  { title: "无题", author: "李商隐", excerptStart: "相见时难别亦难", excerptEnd: "青鸟殷勤为探看" },
  { title: "相见欢", author: "李煜", excerptStart: "无言独上西楼", excerptEnd: "别是一般滋味在心头" },
  { title: "渔家傲·秋思", author: "范仲淹", excerptStart: "塞下秋来风景异", excerptEnd: "将军白发征夫泪" },
  { title: "浣溪沙", author: "晏殊", excerptStart: "一曲新词酒一杯", excerptEnd: "似曾相识燕归来" },
  { title: "登飞来峰", author: "王安石", excerptStart: "飞来山上千寻塔", excerptEnd: "自缘身在最高层" },
  { title: "江城子·密州出猎", author: "苏轼", excerptStart: "老夫聊发少年狂", excerptEnd: "西北望，射天狼" },
  { title: "水调歌头", author: "苏轼", excerptStart: "明月几时有", excerptEnd: "千里共婵娟" },
  { title: "游山西村", author: "陆游", excerptStart: "莫笑农家腊酒浑", excerptEnd: "拄杖无时夜叩门" },
  { title: "南乡子·登京口北固亭有怀", author: "辛弃疾", excerptStart: "何处望神州", excerptEnd: "坐断东南战未休" },
  { title: "破阵子·为陈同甫赋壮词以寄之", author: "辛弃疾", excerptStart: "醉里挑灯看剑", excerptEnd: "可怜白发生" },
  { title: "过零丁洋", author: "文天祥", excerptStart: "辛苦遭逢起一经", excerptEnd: "留取丹心照汗青" },
  { title: "天净沙·秋思", author: "马致远", excerptStart: "枯藤老树昏鸦", excerptEnd: "断肠人在天涯" },
  { title: "山坡羊·潼关怀古", author: "张养浩", excerptStart: "峰峦如聚", excerptEnd: "亡，百姓苦" },
  { title: "己亥杂诗", author: "龚自珍", excerptStart: "浩荡离愁白日斜", excerptEnd: "化作春泥更护花" },
  { title: "满江红", author: "秋瑾", excerptStart: "小住京华", excerptEnd: "青衫湿" },
  { title: "论语十二则", author: "《论语》", excerptStart: "学而时习之", excerptEnd: "切问而近思" },
  { title: "曹刿论战", author: "《左传》", excerptStart: "十年春，齐师伐我", excerptEnd: "遂逐齐师" },
  { title: "鱼我所欲也", author: "孟子", excerptStart: "鱼，我所欲也", excerptEnd: "此之谓失其本心" },
  { title: "河中石兽", author: "纪昀", excerptStart: "沧州南一寺临河干", excerptEnd: "可据理臆断欤" },
  { title: "生于忧患，死于安乐", author: "孟子", excerptStart: "舜发于畎亩之中", excerptEnd: "然后知生于忧患而死于安乐也" },
  { title: "得道多助，失道寡助", author: "孟子", excerptStart: "天时不如地利", excerptEnd: "战必胜矣" },
  { title: "列子一则", author: "《列子》", excerptStart: "伯牙善鼓琴", excerptEnd: "吾于何逃声哉" },
  { title: "邹忌讽齐王纳谏", author: "《战国策》", excerptStart: "邹忌修八尺有余", excerptEnd: "战胜于朝廷" },
  { title: "出师表", author: "诸葛亮", excerptStart: "先帝创业未半而中道崩殂", excerptEnd: "不知所言" },
  { title: "桃花源记", author: "陶渊明", excerptStart: "晋太元中，武陵人捕鱼为业", excerptEnd: "后遂无问津者" },
  { title: "答谢中书书", author: "陶弘景", excerptStart: "山川之美，古来共谈", excerptEnd: "未复有能与其奇者" },
  { title: "三峡", author: "郦道元", excerptStart: "自三峡七百里中", excerptEnd: "良多趣味" },
  { title: "马说", author: "韩愈", excerptStart: "世有伯乐，然后有千里马", excerptEnd: "其真不知马也" },
  { title: "陋室铭", author: "刘禹锡", excerptStart: "山不在高，有仙则名", excerptEnd: "何陋之有" },
  { title: "小石潭记", author: "柳宗元", excerptStart: "从小丘西行百二十步", excerptEnd: "乃记之而去" },
  { title: "岳阳楼记", author: "范仲淹", excerptStart: "庆历四年春", excerptEnd: "吾谁与归" },
  { title: "醉翁亭记", author: "欧阳修", excerptStart: "环滁皆山也", excerptEnd: "太守谓谁？庐陵欧阳修也" },
  { title: "爱莲说", author: "周敦颐", excerptStart: "水陆草木之花", excerptEnd: "同予者何人" },
  { title: "记承天寺夜游", author: "苏轼", excerptStart: "元丰六年十月十二日夜", excerptEnd: "但少闲人如吾两人者耳" },
  { title: "送东阳马生序", author: "宋濂", excerptStart: "余幼时即嗜学", excerptEnd: "盖余之勤且艰若此" },
  { title: "湖心亭看雪", author: "张岱", excerptStart: "崇祯五年十二月", excerptEnd: "舟子喃喃曰" },
  { title: "富贵不能淫", author: "孟子", excerptStart: "景春曰", excerptEnd: "此之谓大丈夫" }
];
